#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Understand-Anything to SkillsBuilder Wiki Bridge
Reads the generated codebase knowledge graph and synchronizes the layers/modules to the local project's wiki/ concepts.
"""

import os
import json
import sys

def sync_graph_to_wiki():
    graph_path = ".understand-anything/knowledge-graph.json"
    if not os.path.exists(graph_path):
        print("[ERROR] .understand-anything/knowledge-graph.json not found.")
        print("[INFO] Please run `/understand` in your project directory first to generate the graph.")
        return False
        
    print(f"[INFO] Reading graph from {graph_path}...")
    try:
        with open(graph_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"[ERROR] Failed to read graph: {e}")
        return False

    os.makedirs("wiki/concepts", exist_ok=True)
    wiki_path = "wiki/concepts/codebase_architecture.md"
    
    print(f"[INFO] Synchronizing graph nodes to {wiki_path}...")
    
    nodes = data.get("nodes", [])
    edges = data.get("edges", [])
    
    # Group nodes by layer/type
    layers = {}
    modules = []
    
    for node in nodes:
        ntype = node.get("type", "unknown")
        name = node.get("name", "")
        desc = node.get("description", "")
        
        if ntype == "layer":
            layers[name] = {"description": desc, "components": []}
        elif ntype == "module" or ntype == "file":
            modules.append(node)
            
    # Associate modules with layers if possible
    # In Understand-Anything, nodes might have a 'layer' field
    for mod in modules:
        mod_name = mod.get("name", "")
        mod_desc = mod.get("description", "")
        mod_layer = mod.get("layer", "Unassigned")
        
        if mod_layer not in layers:
            layers[mod_layer] = {"description": "Auto-detected architectural layer", "components": []}
            
        layers[mod_layer]["components"].append((mod_name, mod_desc))

    try:
        with open(wiki_path, "w", encoding="utf-8") as out:
            out.write("# Codebase Architecture (Understand-Anything Graph)\n\n")
            out.write("> [!NOTE]\n")
            out.write("> This documentation is automatically generated by the `understand_bridge.py` tool from the local `.understand-anything/` knowledge graph. Do not edit manually.\n\n")
            
            out.write("## Architectural Layers\n\n")
            for layer_name, info in sorted(layers.items()):
                out.write(f"### 📦 Layer: {layer_name}\n")
                out.write(f"*{info['description']}*\n\n")
                
                if info["components"]:
                    out.write("| Component / File | Description |\n")
                    out.write("| --- | --- |\n")
                    for comp_name, comp_desc in sorted(info["components"]):
                        # Clean up descriptions
                        clean_desc = comp_desc.replace("\n", " ").strip()
                        out.write(f"| `{comp_name}` | {clean_desc} |\n")
                    out.write("\n")
                else:
                    out.write("*No components mapped to this layer.*\n\n")
                    
            out.write("## Graph Statistics\n\n")
            out.write(f"- **Total Nodes**: {len(nodes)}\n")
            out.write(f"- **Total Edges (Dependencies)**: {len(edges)}\n")
            
        print(f"[SUCCESS] Codebase architecture successfully synced to {wiki_path}!")
        return True
    except Exception as e:
        print(f"[ERROR] Failed to write wiki document: {e}")
        return False

if __name__ == "__main__":
    success = sync_graph_to_wiki()
    sys.exit(0 if success else 1)
